version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.19.4
    ports:
      - "8000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/src/static
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/src/static

    command: bash -c "python manage.py migrate &&
      python manage.py collectstatic --no-input --clear && python manage.py loaddata personajes

volumes:
  static_volume: