# Generated by Django 3.1.2 on 2022-10-27 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winnerpl', to='character.character'),
        ),
    ]
