# Generated by Django 3.1.2 on 2022-10-27 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
        ('fight', '0002_auto_20221026_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='character.character'),
            preserve_default=False,
        ),
    ]
