# Generated by Django 3.1.2 on 2022-10-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0003_history_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='hit',
        ),
        migrations.AddField(
            model_name='history',
            name='relato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
